version: "3.6"
services:

  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    network_mode: bridge # bad design, fixme sometime
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=${POSTMASTER_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - "letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  secretify-api:
    container_name: secretify-api
    network_mode: bridge # bad design, fixme sometime
    restart: always
    image: registry.gravitir.io/secretify/secretify-ee-api:v0.8.23-rc28
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.secretify-api.rule=Host(`${FQDN}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.secretify-api.entrypoints=websecure"
      - "traefik.http.routers.secretify-api.tls.certresolver=myresolver"
      - "traefik.http.services.docker-secretify-api.loadbalancer.server.port=8800"
    environment:
      DEBUG: ${DEBUG}
      LOG_LEVEL: ${LOG_LEVEL}
      ACTIVITY_ENABLED: ${ACTIVITY_ENABLED}
      UI_URL: ${SCHEME}${FQDN}
      META_NAME: ${META_NAME}
      META_ADDRESS: ${META_ADDRESS}
      META_EMAIL: ${META_EMAIL}
      STORAGE_ENABLED: ${STORAGE_ENABLED}
      STORAGE_SPACELEFT_HEALTHCHECK: ${STORAGE_SPACELEFT_HEALTHCHECK}
      STORAGE_SPACELEFT_THRESHOLD: ${STORAGE_SPACELEFT_THRESHOLD}
      STORAGE_FILESYSTEM_ENABLED: ${STORAGE_FILESYSTEM_ENABLED}
      STORAGE_ALLOWEDFILEEXTENSIONS: "${STORAGE_ALLOWEDFILEEXTENSIONS}"
      AUTH_ENABLED: ${AUTH_ENABLED}
      AUTH_STRICT: ${AUTH_STRICT}
      AUTH_SESSIONSECRET: ${AUTH_SESSIONSECRET}
      AUTH_MICROSOFTONLINE_ENABLED: ${AUTH_MICROSOFTONLINE_ENABLED}
      AUTH_MICROSOFTONLINE_SCOPES: ${AUTH_MICROSOFTONLINE_SCOPES}
      AUTH_MICROSOFTONLINE_CLIENTID: ${AUTH_MICROSOFTONLINE_CLIENTID}
      AUTH_MICROSOFTONLINE_CLIENTSECRET: ${AUTH_MICROSOFTONLINE_CLIENTSECRET}
      AUTH_MICROSOFTONLINE_TENANT: ${AUTH_MICROSOFTONLINE_TENANT}
      AUTH_MICROSOFTONLINE_REDIRECTURL: ${AUTH_MICROSOFTONLINE_REDIRECTURL}
      AUTH_MICROSOFTONLINE_APPLICATIONID: ${AUTH_MICROSOFTONLINE_APPLICATIONID}
      AUTH_MICROSOFTONLINE_APPLICATIONIDURI: ${AUTH_MICROSOFTONLINE_APPLICATIONIDURI}
      PLUGIN_OUTLOOK_ENABLED: ${PLUGIN_OUTLOOK_ENABLED}
      PLUGIN_OUTLOOK_APPID: ${PLUGIN_OUTLOOK_APPID}
      PLUGIN_OUTLOOK_APPVERSION: ${PLUGIN_OUTLOOK_APPVERSION}
      MAIL_ENABLED: ${MAIL_ENABLED}
      MAIL_SMTP_FROM: ${MAIL_SMTP_FROM}
      MAIL_SMTP_USERNAME: ${MAIL_SMTP_USERNAME}
      MAIL_SMTP_PASSWORD: ${MAIL_SMTP_PASSWORD}
      MAIL_SMTP_HOST: ${MAIL_SMTP_HOST}
      MAIL_SMTP_PORT: ${MAIL_SMTP_PORT}
      SERVE_ADDRESS: ${SERVE_ADDRESS}
      SERVE_BASEPATH: ${SERVE_BASEPATH}
      SERVE_STATICFOLDER: ${SERVE_STATICFOLDER}
      SERVE_TLS: ${SERVE_TLS}
      SERVE_TLS_CERTIFLE: ${SERVE_TLS_CERTIFLE}
      SERVE_TLS_KEYFILE: ${SERVE_TLS_KEYFILE}
      SERVE_READTIMEOUT: ${SERVE_READTIMEOUT}
      SERVE_WRITETIMEOUT: ${SERVE_WRITETIMEOUT}
      SERVE_CORS_ENABLED: ${SERVE_CORS_ENABLED}
      SERVE_CORS_ALLOWEDORIGINS: ${SERVE_CORS_ALLOWEDORIGINS}
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
    volumes:
      - db:/db
      - files:/_files
      - ./static:/static
      - ./config:/config

  secretify-ui:
    container_name: secretify-ui
    network_mode: bridge # bad design, fixme sometime
    restart: always
    image: registry.gravitir.io/secretify/secretify-ee-ui:v0.8.23-rc28
    depends_on:
      - secretify-api
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.secretify-ui.rule=Host(`${FQDN}`)"
      - "traefik.http.routers.secretify-ui.entrypoints=websecure"
      - "traefik.http.routers.secretify-ui.tls.certresolver=myresolver"
      - "traefik.http.services.docker-secretify-ui.loadbalancer.server.port=3000"
    environment:
      API_URL: "${SCHEME}${FQDN}/api/v1"
      LOCAL_API_URL: "${SCHEME}${FQDN}/api/v1"
      UI_URL: "${SCHEME}${FQDN}"
      AUTH_RANDOM_GUESTNAME: "${AUTH_RANDOM_GUESTNAME}"
      BRANDING_SERIOUS: "${BRANDING_SERIOUS}"
      BRANDING_PRIMARY_COLOR: "${BRANDING_PRIMARY_COLOR}"
      BRANDING_LOGO: "${SCHEME}${FQDN}/api/v1/static/${BRANDING_LOGO}"
      BRANDING_MARKETING: ${BRANDING_MARKETING}
      HELP_ENABLED: ${HELP_ENABLED}
      PASSWORDGENERATOR_LENGTH: ${PASSWORDGENERATOR_LENGTH}

volumes:
  letsencrypt:
  db:
  files:
