# Additional Secretify config
types:
  # Default text
  - active: true
    identifier: text
    name:
      en: Text
    description:
      en: This secret type allows you to create confidential text messages.
    schema:
      - property: message # use lowercase only
        type: string
        required: true
        secretMaxLength: 500
    uiSetting:
      order: 1
      secretRevealDuration: "60s"
      secretExpiresInOptions: # valid are s (seconds), m (minutes) and h (hours)
        - "5m"
        - "1h"
        - "24h"
        - "168h"
      displayName:
        message:
          en: Message
      description:
        message:
          en: The message is end-to-end encrypted. The key is added to the link but won't be stored.
      placeholder:
        message:
          en: Compose your confidential message here
    policy:
      defaultSecretMaxLength: 500
  # Default file
  - active: true
    identifier: file
    name:
      en: File
    description:
      en: This secret type allows you to upload files with optional details.
    schema:
      - property: file # use lowercase only
        type: file
        required: true
        maxFilesize: 104857600 # 100MB in bytes
        allowedFileExtensions:
          - .jpeg
          - .jpg
          - .gif
          - .png
          - .eps
          - .raw
          - .tif
          - .tiff
          - .bmp
          - .log
          - .txt
          - .key
          - .pem
          - .csv
          - .zip
      - property: details
        type: string
        required: false
        secretMaxLength: 200
    uiSetting:
      order: 2
      secretRevealDuration: "120s"
      secretExpiresInOptions: # valid are s (seconds), m (minutes) and h (hours)
        - "5m"
        - "1h"
        - "24h"
        - "168h"
      displayName:
        file:
          en: File
        details:
          en: Details
      description:
        details:
          en: Add an optional message related to the uploaded file.
      placeholder:
        details:
          en: Details to go along with the file
    policy:
      defaultSecretMaxLength: 500 # if secretMaxLength in schema is not set
      defaultMaxFilesize: 10000 # if maxFilesize in schema is not set