# Additional Secretify config

types:
  # Default text
  - active: true
    identifier: text
    name: Text
    description: ""
    schema:
      message:
        displayName: Message_editme
        placeholder: Compose your confidential message here_editme
        type: string
        description: "The message is end-to-end encrypted. The key is added to the link but won't be stored._editme"
    option:
      order: 1
      secretRevealDuration: "60s"
      secretExpiresInOptions:
        - "5m"
        - "1h"
        - "24h"
        - "168h"
    policy:
      secretMaxLength: 500
    isFile: false
  # Default file
  - active: true
    identifier: file
    name: File
    description: ""
    schema:
      message:
        displayName: Message_editme
        placeholder: Details to go along with the file_editme
        type: string
        description: "Add an optional message related to the uploaded file._editme"
    option:
      order: 2
      secretRevealDuration: "120s"
      secretExpiresInOptions:
        - "5m"
        - "1h"
        - "24h"
        - "168h"
    policy:
      secretMaxLength: 200
    isFile: true