# Additional Secretify config

types:
  - active: true
    identifier: credentials
    name: Credentials
    description: ""
    order: 5
    schema: |
      {
        "username": {
          "type": "string",
          "display_name": "Username",
          "description": "Instead of providing only a text message, you can split the message into credentials by providing a username.."
        },
        "password": {
          "type": "string",
          "display_name": "Password",
          "description": "..and a password."
        }
      }
    secretMaxLength: 150